# Generated by Django 6.1.1 on 2026-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='detected_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
    ]
