# Generated by Django 6.1.1 on 2026-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_resume_detected_skills_resume_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='nlp_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
