# Generated by Django 6.1.1 on 2026-10-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_resume_nlp_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skill_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
